/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf --transform -t
Author: SCD PERFORMANCE™️ (https://sketchfab.com/3Duamodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-macbook-pro-a1708tm-ab76d536f0b943648b7e758ce9301b90
Title: Apple-macbook-pro-a1708™️
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
    defaultMaterial_4: THREE.Mesh
  }
  materials: {
    apple_a1708_macbook_pro_13_mpxq2ua_space_gray_decol_mat: THREE.MeshStandardMaterial
    apple_a1708_macbook_pro_13_mpxq2ua_space_gray_main_mat: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/mac-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_decol_mat} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_decol_mat} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_main_mat} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_decol_mat} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.apple_a1708_macbook_pro_13_mpxq2ua_space_gray_main_mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mac-transformed.glb')
